"""
AI Tool Portal — Tool Registry
Single source of truth for all monitored services.
Each entry: id, name, category, icon, port, detection, version, action.
"""
from pathlib import Path

# Base paths
HOME = Path.home()
DRIVE_AI = Path("/mnt/d/AI")

TOOLS = [
    # ── Gateways ────────────────────────────────────────────────
    {
        "id": "openclaw",
        "name": "OpenClaw",
        "category": "gateway",
        "icon": "Bot",
        "default_port": 18789,
        "version_cmd": ["openclaw", "--version"],
        "version_pattern": r"OpenClaw\s+([0-9.]+)",
        "process_patterns": ["openclaw-gateway", "dist/index.js gateway --port"],
        "process_comm_filter": "node",
        "port_range": [18789],
        "start_cmd": "systemctl --user start openclaw-gateway",
        "stop_cmd": "systemctl --user stop openclaw-gateway",
        "restart_cmd": "systemctl --user restart openclaw-gateway",
        "log_paths": [str(HOME / ".openclaw/logs")],
    },
    {
        "id": "hermes_gateway",
        "name": "Hermes Gateway",
        "category": "gateway",
        "icon": "Gateway",
        "default_port": 9119,
        "version_cmd": ["hermes", "--version"],
        "version_pattern": r"hermes\s+([0-9.]+)",
        "process_patterns": ["hermes_cli.main gateway"],
        "process_comm_filter": "python",
        "port_range": [9119],
        "start_cmd": f"cd {HOME}/.hermes/hermes-agent && {HOME}/.hermes/hermes-agent/venv/bin/python -m hermes_cli.main gateway run --replace",
        "stop_cmd": "pkill -f 'hermes_cli.main gateway'",
        "restart_cmd": "pkill -f 'hermes_cli.main gateway' && sleep 2",
        "log_paths": [str(HOME / ".hermes/logs/gateway.log")],
    },
    {
        "id": "hermes_dashboard",
        "name": "Hermes Dashboard",
        "category": "gateway",
        "icon": "LayoutDashboard",
        "default_port": 9119,
        "version_cmd": ["hermes", "--version"],
        "version_pattern": r"hermes\s+([0-9.]+)",
        "process_patterns": ["hermes dashboard"],
        "process_comm_filter": "python",
        "port_range": [9119],
        "start_cmd": f"hermes dashboard --port 9119",
        "stop_cmd": "pkill -f 'hermes dashboard'",
        "restart_cmd": "pkill -f 'hermes dashboard' && sleep 2",
        "log_paths": [str(HOME / ".hermes/logs/dashboard_restart.log")],
    },
    # ── Workflow / Scheduler ─────────────────────────────────────
    {
        "id": "n8n",
        "name": "n8n",
        "category": "workflow",
        "icon": "Workflow",
        "default_port": 5678,
        "version_cmd": ["n8n", "--version"],
        "version_pattern": r"([0-9.]+)",
        "process_patterns": [],
        "process_comm_filter": None,
        "port_range": [5678],
        "docker_ancestry": "n8nio/n8n",
        "start_cmd": "cd /mnt/d/Docker && docker compose -f n8n-restored.yml up -d",
        "stop_cmd": "cd /mnt/d/Docker && docker compose -f n8n-restored.yml down",
        "restart_cmd": "cd /mnt/d/Docker && docker compose -f n8n-restored.yml restart",
        "log_paths": ["/mnt/d/Docker/n8n-data/logs"],
    },
    {
        "id": "prayer_server",
        "name": "Prayer Pipeline v3",
        "category": "scheduler",
        "icon": "Prayer",
        "default_port": 5000,
        "version_pattern": r"v([0-9.]+)",
        "process_patterns": ["prayer_server_v3"],
        "process_comm_filter": "python",
        "port_range": [5000],
        "start_cmd": f"cd {HOME}/.hermes/scripts && nohup {HOME}/.hermes/hermes-agent/venv/bin/python prayer_server_v3.py > {HOME}/.hermes/logs/prayer_server.log 2>&1 &",
        "stop_cmd": "pkill -f 'prayer_server_v3'",
        "restart_cmd": "pkill -f 'prayer_server_v3' && sleep 2",
        "log_paths": [str(HOME / ".hermes/logs/prayer_server.log")],
    },
    # ── ComfyUI instances ────────────────────────────────────────
    {
        "id": "comfyui_3d",
        "name": "ComfyUI — 3D",
        "category": "ai_image",
        "icon": "Image",
        "dir": str(DRIVE_AI / "ComfyUI_3D"),
        "launcher": str(DRIVE_AI / "ComfyUI_3D/run_3d.sh"),
        "default_port": 8190,
        "version_pattern": r"ComfyUI[_\s]([0-9.]+)",
        "process_patterns": ["ComfyUI_3D"],
        "process_comm_filter": "python",
        "port_range": [8190],
    },
    {
        "id": "comfyui_ideogram",
        "name": "ComfyUI — Ideogram",
        "category": "ai_image",
        "icon": "Image",
        "dir": str(DRIVE_AI / "ComfyUI_Ideogram"),
        "launcher": str(DRIVE_AI / "ComfyUI_Ideogram/start_ideogram.sh"),
        "default_port": 8194,
        "version_pattern": r"ComfyUI[_\s]([0-9.]+)",
        "process_patterns": ["ComfyUI_Ideogram"],
        "process_comm_filter": "python",
        "port_range": [8194],
    },
    {
        "id": "comfyui_ltx",
        "name": "ComfyUI — LTX Video",
        "category": "ai_video",
        "icon": "Video",
        "dir": str(DRIVE_AI / "ComfyUI_LTX"),
        "launcher": str(DRIVE_AI / "ComfyUI_LTX/run_comfyui.sh"),
        "default_port": 8183,
        "version_pattern": r"ComfyUI[_\s]([0-9.]+)",
        "process_patterns": ["ComfyUI_LTX"],
        "process_comm_filter": "python",
        "port_range": [8183],
    },
    {
        "id": "comfyui_heartmula",
        "name": "ComfyUI — Heartmula",
        "category": "ai_audio",
        "icon": "Music",
        "dir": str(DRIVE_AI / "ComfyUI_Heartmula"),
        "launcher": str(DRIVE_AI / "ComfyUI_Heartmula/run_audio.sh"),
        "default_port": 8189,
        "version_pattern": r"ComfyUI[_\s]([0-9.]+)",
        "process_patterns": ["ComfyUI_Heartmula"],
        "process_comm_filter": "python",
        "port_range": [8189],
    },
    {
        "id": "comfyui_krita",
        "name": "ComfyUI — Krita",
        "category": "ai_image",
        "icon": "Image",
        "dir": str(DRIVE_AI / "ComfyUI_Krita"),
        "launcher": str(DRIVE_AI / "ComfyUI_Krita/run_comfyui.bat"),
        "launcher_type": "bat",
        "default_port": 8192,
        "version_pattern": r"ComfyUI[_\s]([0-9.]+)",
        "process_patterns": ["ComfyUI_Krita"],
        "process_comm_filter": "python",
        "port_range": [8192],
    },
    {
        "id": "comfyui_standard",
        "name": "ComfyUI — Standard",
        "category": "ai_image",
        "icon": "Image",
        "dir": str(DRIVE_AI / "ComfyUI_Standard"),
        "launcher": str(DRIVE_AI / "ComfyUI_Standard/run_standard.bat"),
        "launcher_type": "bat",
        "default_port": 8188,
        "version_pattern": r"ComfyUI[_\s]([0-9.]+)",
        "process_patterns": ["ComfyUI_Standard"],
        "process_comm_filter": "python",
        "port_range": [8188],
    },
    {
        "id": "comfyui_qwen3tts",
        "name": "ComfyUI — Qwen3-TTS",
        "category": "ai_audio",
        "icon": "Music",
        "dir": str(DRIVE_AI / "ComfyUI_Qwen3-TTS"),
        "launcher": str(DRIVE_AI / "ComfyUI_Qwen3-TTS/run_audio.sh"),
        "default_port": 8189,
        "version_pattern": r"ComfyUI[_\s]([0-9.]+)",
        "process_patterns": ["ComfyUI_Qwen3-TTS"],
        "process_comm_filter": "python",
        "port_range": [8189],
    },
    {
        "id": "comfyui_win_data",
        "name": "ComfyUI — win_data",
        "category": "ai_image",
        "icon": "Image",
        "dir": str(DRIVE_AI / "ComfyUI_win_data"),
        "launcher": str(DRIVE_AI / "ComfyUI_win_data/ComfyUI.exe"),
        "launcher_type": "exe",
        "default_port": 8186,
        "version_pattern": r"ComfyUI[_\s]([0-9.]+)",
        "process_patterns": ["ComfyUI_win_data"],
        "process_comm_filter": None,
        "port_range": [8186],
    },
    {
        "id": "comfyui_documents",
        "name": "ComfyUI — Documents",
        "category": "ai_image",
        "icon": "Image",
        "dir": str(DRIVE_AI / "ComfyUI_Documents"),
        "default_port": 8191,
        "version_pattern": r"ComfyUI[_\s]([0-9.]+)",
        "process_patterns": ["ComfyUI_Documents"],
        "process_comm_filter": "python",
        "port_range": [8191],
    },
]

CATEGORIES = [
    {"id": "gateway", "label": "Gateways", "icon": "Gateway"},
    {"id": "workflow", "label": "Workflow Engines", "icon": "Workflow"},
    {"id": "scheduler", "label": "Schedulers", "icon": "Clock"},
    {"id": "ai_image", "label": "AI Image", "icon": "Image"},
    {"id": "ai_video", "label": "AI Video", "icon": "Video"},
    {"id": "ai_audio", "label": "AI Audio", "icon": "Music"},
]


def get_tool(id: str):
    return next((t for t in TOOLS if t["id"] == id), None)